name: contact_heatmaps_ml

channels:
  - conda-forge
  - pytorch
  - open3d-admin

dependencies:
  - python=3.6.6
  - open3d
  - trimesh
  - pytorch=0.4.1
  - torchvision
  - matplotlib
  - ignite
  - pip
  - pip:
      - visdom
      - transforms3d
